name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12
    - name: Build site
      env:
        PUBLIC_PATH: '/asb-client-spa/'
      run: |
        npm ci
        npm run build
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        commit_message: 'GitHub Actions automated deployment'
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
        user_name: 'github-actions[bot]'
        user_email: 'github-actions[bot]@users.noreply.github.com'
    - name: Notify Slack
      uses: rtCamp/action-slack-notify@master
      env:
        MSG_MINIMAL: true
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
